// List of libraries produced by library-helper.py. DO NOT EDIT
"/usr/lib/libpvr2d_r125.so",
"/usr/lib/libpvrPVR2D_DRI2WSEGL_r125.so",
"/usr/lib/qt4/plugins/imageformats/libqsvg.so",
"/usr/lib/qt4/plugins/imageformats/libqico.so",
"/usr/lib/qt4/plugins/imageformats/libqtiff.so",
"/usr/lib/libambase.so",
"/usr/lib/qt4/plugins/imageformats/libqgif.so",
"/usr/lib/qt4/plugins/inputmethods/libminputcontext.so",
"/usr/lib/qt4/plugins/inputmethods/libqimsw-multi.so",
"/usr/lib/qt4/plugins/graphicssystems/libqmeegographicssystem.so",
"/usr/lib/contextkit/subscriber-plugins/kbslider-1.so",
"/usr/lib/libGLESv2_r125.so",
"/usr/lib/libIMGegl_r125.so",
"/usr/lib/libEGL_r125.so",
"/usr/lib/gconv/UTF-16.so",
"/usr/lib/libsrv_um_r125.so",
"/usr/lib/libmlocale.so",
